### PR TITLE
Improvements to the documentation navigation

### PR DESCRIPTION
**Pull request by russelltrow**
Updated the navigation structure to make the documentation easier to use

Screenshot 2023-10-04 at 17 51 54

### CODE REVIEW

**Comment by Henry-WattTime** [comment]
Do you think it would be possible to put all the project related pages under a single heading? Add some hierarchy to the sidebar? I don't think the project inactivity policies are as important as the OC Responsibilities for example.

**Comment by russelltrow** [comment]
> Do you think it would be possible to put all the project related pages under a single heading? Add some hierarchy to the sidebar? I don't think the project inactivity policies are as important as the OC Responsibilities for example.

How does this look?

Screenshot 2023-10-05 at 09 31 24

**Comment by Henry-WattTime** [comment]
This looks great!

**Comment by russelltrow** [comment]
@tmcclell @Sealjay are you happy for this to be merged?

**Pull request merged**
